Dokumentation: Erweiterungen + Aufräumarbeiten
RvNovae/dhge-latex pull request #100
Opened 2021-08-16 16:03 UTC by ZeroPointMax

Ich habe die Issues #21 und #92 in Angriff genommen schlage das hier als Lösung vor; insofern die verhängnisvollen Worte:

resolves #21 

resolves #92 

Weiters habe ich ein paar Kleinigkeiten aufgehübscht und hier und da was ergänzt. Ich hatte da auch im Hinterkopf, dass auch nicht IT-ler vielleicht das Repo benutzen wollen und mich an so einem ungefähren Niveau orientiert.

Mehr Details im Commit-Log

2021-08-21 11:01 UTC, RvNovae approved these changes
Nur ein paar Kleinigkeiten, ansonsten super!

Vielen dank für die tollen Verbesserungen der Doku :)

2021-08-21 11:01 UTC, RvNovae commented on README.md
> +Wir empfehlen für die Arbeit in Visual Studio Code ausgewählte Erweiterungen, die sowohl für das Schreiben mit LaTeX, als auch für das Studium an der DHGE<!--ähem Plantuml--> hilfreich sind.
😆

2021-08-21 11:01 UTC, RvNovae commented on README.md
> +Z.B. kann ein externer PDF-Betrachter oder ein automatisches Build-Intervall eingerichtet werden.
```suggestion
z.B. kann ein externer PDF-Betrachter oder ein automatisches Build-Intervall eingerichtet werden.
```

2021-08-21 11:01 UTC, RvNovae commented on README.md
> +> Hier ist zu beachten, dass nach der Variable das Leerzeichen fehlen wird, da dieses als Argument des Befehls aufgenommen wird
Vielleicht könnte man hier noch erwähnen, dass, wenn man das Leerzeichen erhalten möchte, man einfach `\<variablenNam>{}` eingeben muss.

2021-08-21 11:01 UTC, RvNovae commented on README.md
> +Falls chinesische, japanische o.ä. Alphabete verwendet werden müssen (bsp. bedingt durch Autoren), ist die einfachste Methode, das `CJKutf8` Package zu laden.
```suggestion
Falls chinesische, japanische o.ä. Alphabete verwendet werden müssen (bspw. bedingt durch Autoren), ist die einfachste Methode, das `CJKutf8` Package zu laden.
```

2021-08-23 08:04 UTC, photovoltex commented on README.md
> +Ein Codeblock, welcher bestimmte Anläufe vor und nach dem eigenen Code laufen lässt.
```suggestion
Ein Codeblock, welcher bestimmte Abläufe vor und nach dem eigenen Code laufen lässt.
```

2021-08-23 08:04 UTC, photovoltex commented on README.md
> +Dafür wird der `footcite` Befehl genutzt. Dieser hat folgende Syntax:
Evtl. lieber etwas anderes als `hat` z.B. `besitzt`.

2021-08-23 08:04 UTC, photovoltex commented on README.md
> +Für einen Einstieg in das wissenschaftliche Schreiben an sich bietet sich ein Artikel von Sebastian Hahner an, der ebenfalls auf LaTeX eingeht: [Wissenschaftliches Schreiben Schnelleinstieg](https://
```suggestion
Für einen Einstieg in das wissenschaftliche Schreiben an sich, bietet sich ein Artikel von Sebastian Hahner an, der ebenfalls auf LaTeX eingeht: [Wissenschaftliches Schreiben Schnelleinstieg](https://github.com/sebinside/WissenschaftlichesSchreiben-Schnelleinstieg)
```
_Bin mir nicht ganz sicher._

2021-08-23 08:12 UTC, photovoltex commented
Ach und einen bietet hätte ich noch... könnte man fie Images verwendet vom repo in einen anderen Ordner halten?
Der `assets/img` Path ist ja eigentlich vorgehalten für das Template^^

Würde empfehlen `assets/md-img` oder etwas ähnliches.

Und auch nocheinmal ein Danke von mir :D

2021-08-23 09:39 UTC, RvNovae commented on README.md
> +Dafür wird der `footcite` Befehl genutzt. Dieser hat folgende Syntax:
Mir persönlich relativ egal, klingt beides gut.
Könnt Ihr beiden entscheiden :^)

2021-08-23 09:40 UTC, RvNovae commented
> Ach und einen bietet hätte ich noch... könnte man die Images verwendet vom repo in einen anderen Ordner halten?
> Der `assets/img` Path ist ja eigentlich vorgehalten für das Template^^
> 
> Würde empfehlen `assets/md-img` oder etwas ähnliches.
> 
> Und auch nocheinmal ein Danke von mir :D

Ja das wäre wahrscheinlich besser, wenn die in einem eigenen Ordner wären.
Vielleicht einfach `assets/readme`.

2021-08-23 09:40 UTC, RvNovae requested changes
Siehe Kommentare

2021-08-28 14:38 UTC, ZeroPointMax commented on README.md
> +Für einen Einstieg in das wissenschaftliche Schreiben an sich bietet sich ein Artikel von Sebastian Hahner an, der ebenfalls auf LaTeX eingeht: [Wissenschaftliches Schreiben Schnelleinstieg](https://
Meine Grammatik-Kenntnisse mögen etwas eingerostet sein, aber ich finde hier keinen Nebensatz 🤔

2021-08-28 14:40 UTC, ZeroPointMax commented on README.md
> +Z.B. kann ein externer PDF-Betrachter oder ein automatisches Build-Intervall eingerichtet werden.
Da alle anderen Stichpunkte groß begonnen wurden, habe ich das Z auch mal groß geschrieben

2021-08-28 14:41 UTC, ZeroPointMax commented on README.md
> +> Hier ist zu beachten, dass nach der Variable das Leerzeichen fehlen wird, da dieses als Argument des Befehls aufgenommen wird
Naja das steht doch oben drüber oder? Da würde ich den Satz lieber umschreiben, sodass da was von "alternativ dazu" steht?

2021-08-28 14:50 UTC, photovoltex commented on README.md
> +Für einen Einstieg in das wissenschaftliche Schreiben an sich bietet sich ein Artikel von Sebastian Hahner an, der ebenfalls auf LaTeX eingeht: [Wissenschaftliches Schreiben Schnelleinstieg](https://
ah jo war mir auch nicht ganz sicher... lassen wir dann so^^

2021-08-28 14:52 UTC, photovoltex commented on README.md
> +Dafür wird der `footcite` Befehl genutzt. Dieser hat folgende Syntax:
@ZeroPointMax, ich nehme mal an du lässt es so?

2021-08-28 15:37 UTC, ZeroPointMax commented on README.md
> +Dafür wird der `footcite` Befehl genutzt. Dieser hat folgende Syntax:
@photovoltex nah, habs auf "besitzt" umgeschrieben

2021-08-28 15:58 UTC, photovoltex commented on README.md
> +Dafür wird der `footcite` Befehl genutzt. Dieser hat folgende Syntax:
weird hätte sich dann eigentlich selbst resolven sollen... naja ¯\_(ツ)_/¯

2021-08-29 09:36 UTC, ZeroPointMax commented
Ich glaube, ich habe jetzt alle Kommentare beantwortet und die Änderungen übernommen?

2021-08-29 12:16 UTC, RvNovae approved these changes

2021-08-29 12:16 UTC, RvNovae commented on README.md
> +> Hier ist zu beachten, dass nach der Variable das Leerzeichen fehlen wird, da dieses als Argument des Befehls aufgenommen wird
Oh stimmt, hast recht.

2021-08-29 12:16 UTC, merged