Fix acro indentation
RvNovae/dhge-latex pull request #111
Opened 2021-12-22 11:29 UTC by RvNovae

Custom acro template definieren -> acro liste wird nun gleichmäßig indentiert.
Ich sehe gerade, dass die Liste insgesamt auch noch indentiert wird. Da muss ich dann vielleicht nochmal schauen, wie sich das noch ändern lässt.

Closes #110

2021-12-22 16:16 UTC, photovoltex requested changes
Abb. 1
![image](https://user-images.githubusercontent.com/36958734/147122154-c849eeb1-1ce5-4bdc-b03a-9db358b66d52.png)
Abb. 2
![image](https://user-images.githubusercontent.com/36958734/147122175-dcf5de9b-dee5-4909-89a0-93290d3e3509.png)

Überschrift und Liste Spacing passt meiner Meinung, ist anscheinend eher das Spacing zwischen den Items.

Würde noch wie bei dem alten (siehe Abb. 1) die "short" Version in bold formatieren.

Ansonsten vielen Dank :D

2021-12-23 07:07 UTC, RvNovae commented
> Überschrift und Liste Spacing passt meiner Meinung, ist anscheinend eher das Spacing zwischen den Items.
> 
> Würde noch wie bei dem alten (siehe Abb. 1) die "short" Version in bold formatieren.
> 
> Ansonsten vielen Dank :D

Ah, guter Fang. Die beiden Sachen muss ich noch machen.

2021-12-23 15:53 UTC, photovoltex approved these changes
Mir gefällt etwas mehr wenn der Abstand zwischen den Abk. etwas kleiner (z.B. 7pt) ist aber so sollte es passen. Very thx^^

2021-12-23 17:15 UTC, RvNovae commented
> Mir gefällt etwas mehr wenn der Abstand zwischen den Abk. etwas kleiner (z.B. 7pt) ist aber so sollte es passen. Very thx^^

Wir können das auch konfigurierbar machen, oder so

2021-12-23 17:41 UTC, photovoltex commented
> > Mir gefällt etwas mehr wenn der Abstand zwischen den Abk. etwas kleiner (z.B. 7pt) ist aber so sollte es passen. Very thx^^
> 
> Wir können das auch konfigurierbar machen, oder so

Kannst du gerne machen, kann aber auch so gemerged werden, ist mir relativ egal^^

2021-12-23 19:38 UTC, merged