Anlagen erlauben nur figure und table
RvNovae/dhge-latex pull request #120
Opened 2022-01-24 11:52 UTC by RvNovae

Eine recht einfache Lösung.

Es wird eine nicht-float figure environment definiert: `longfigure`
Diese kann wie eine ganz normale figure environment verwendet werden, kann jedoch über Seitengrenzen hinweg gehen.

Funktioniert auf jeden Fall, wäre jedoch die Frage, ob es nicht eine elegantere Lösung gibt.

Closes #118

2022-01-24 14:32 UTC, ZeroPointMax reviewed
Die Idee finde ich gut. Habe ich richtig verstanden, was hier passiert?

Es wird ein neues Environment vom Typ "figure" definiert (aka wird von LaTeX als Bild gesehen). Dann wird es mit dem Anlagen-Zähler verkuppelt, wieder als Typ Bild?

2022-01-24 14:56 UTC, RvNovae commented
> Die Idee finde ich gut. Habe ich richtig verstanden, was hier passiert?
> 
> Es wird ein neues Environment vom Typ "figure" definiert (aka wird von LaTeX als Bild gesehen). Dann wird es mit dem Anlagen-Zähler verkuppelt, wieder als Typ Bild?

Korrekt!

2022-01-25 07:20 UTC, ZeroPointMax approved these changes

2022-01-26 09:23 UTC, photovoltex requested changes
DOKU 👏

2022-02-07 16:05 UTC, ZeroPointMax approved these changes
Löst das Problem 👍

Einen Nachteil bei Kusche hat es: Listings werden als Abbildung geführt, was bei wenigen Listings OK ist, aber bei vielen er ein eigenes Verzeichnis haben will. Das ist dann aber glaube eh ein Randfall

2022-02-07 16:15 UTC, RvNovae commented
> Löst das Problem 👍
> 
> Einen Nachteil bei Kusche hat es: Listings werden als Abbildung geführt, was bei wenigen Listings OK ist, aber bei vielen er ein eigenes Verzeichnis haben will. Das ist dann aber glaube eh ein Randfall

Man könnte eh noch ein `longlisting` definieren, wenn sowas gebraucht wird. Oder man findet irgendwie eine generische Lösung.

2022-02-07 16:19 UTC, photovoltex commented
> > Löst das Problem 👍
> > Einen Nachteil bei Kusche hat es: Listings werden als Abbildung geführt, was bei wenigen Listings OK ist, aber bei vielen er ein eigenes Verzeichnis haben will. Das ist dann aber glaube eh ein Randfall
> 
> Man könnte eh noch ein `longlisting` definieren, wenn sowas gebraucht wird. Oder man findet irgendwie eine generische Lösung.

Diese generische Lösung wollte ich mal bereitstellen, hatte bisher leider noch nicht die Motivation dazu :/
Wäre am Ende optimalerweise eine einzige Addition in der Anlage (Enivorment unabgängig)

2022-02-07 16:37 UTC, RvNovae commented
Optimal wäre meiner Meinung nach so eine Art `nonfloat` bei der man den Typen (also welcher Auflistungs-Art er zugeordnet wird) per Parameter mitgeben kann.

2022-02-07 16:43 UTC, ZeroPointMax commented
> Optimal wäre meiner Meinung nach so eine Art `nonfloat` bei der man den Typen (also welcher Auflistungs-Art er zugeordnet wird) per Parameter mitgeben kann.

Oh das klingt sexy

2022-02-10 19:40 UTC, photovoltex approved these changes
Würde ein follow-up issue erstellen da dieser PR eigentlich durch ist.

2022-02-10 19:43 UTC, RvNovae commented
> Würde ein follow-up Issue erstellen da dieser PR eigentlich durch ist.

Klingt vernünftig, danke!

2022-02-10 19:43 UTC, merged