Fix Freigabe formatting when using indentations
RvNovae/dhge-latex pull request #133
Opened 2022-05-03 11:52 UTC by RvNovae

Vor der Ehrenwörtlichen Erklärung und Freigabe wird nun einfach die Einrückungen einfach wieder resettet.
Dadurch wird bei `\def\CEINR {1}` die freigabe nun korrekt dargestellt.

2022-05-04 09:15 UTC, ZeroPointMax requested changes
Passt. Betrifft ja

2022-05-04 09:15 UTC, ZeroPointMax commented on build/template.tex
>      % EHRENWÖRTLICHE ERKLÄRUNG
```suggestion
        \fi
    \fi
    
    % Einrückung und Abstand unabhängig von config.tex setzen: Ehrenwort und Freigabe korrekt formatiert
    \setlength{\parskip}{6pt}
    \setlength{\parindent}{0cm}

    % EHRENWÖRTLICHE ERKLÄRUNG

```

Ähem, du hast was vergessen ;)

2022-05-04 13:44 UTC, RvNovae commented on build/template.tex
>      % EHRENWÖRTLICHE ERKLÄRUNG
Danke, (wie immer) voll vergessen.

2022-05-04 18:21 UTC, photovoltex approved these changes
Sounds about right.

2022-05-05 06:12 UTC, ZeroPointMax approved these changes

2022-05-05 06:12 UTC, merged